AllCops:
  Exclude:
    - _site/**/*
    - node_modules/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
